# Generated by Django 5.0.7 on 2024-08-09 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_job_delete_skill_delete_training_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='skills/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['-created'],
            },
        ),
    ]
