# Generated by Django 5.0.7 on 2024-08-14 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Compania'),
        ),
    ]
