# Generated by Django 5.0.7 on 2024-08-15 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_alter_job_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='years_experience',
            field=models.IntegerField(default=0),
        ),
    ]
