# Generated by Django 5.0.7 on 2024-08-15 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_alter_skill_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['years_experience'], 'verbose_name': 'Skill', 'verbose_name_plural': 'Skills'},
        ),
    ]
