# Generated by Django 5.0.7 on 2024-08-19 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_alter_skill_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-end_date'], 'verbose_name': 'Job', 'verbose_name_plural': 'Jobs'},
        ),
        migrations.RenameField(
            model_name='job',
            old_name='date',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='job',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='job',
            name='image',
        ),
        migrations.AddField(
            model_name='job',
            name='achievements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='company_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='responsibilities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='technologies_used',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='work_mode',
            field=models.CharField(choices=[('remote', 'Remoto'), ('hybrid', 'Híbrido'), ('onsite', 'Presencial')], default='onsite', max_length=10),
        ),
    ]
