# Generated by Django 5.0.7 on 2024-08-19 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_alter_job_options_rename_date_job_start_date_and_more'),
        ('portfolio', '0007_tag_color_alter_projects_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='technologies_used',
        ),
        migrations.AlterField(
            model_name='job',
            name='work_mode',
            field=models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'Onsite')], default='onsite', max_length=10),
        ),
        migrations.AddField(
            model_name='job',
            name='technologies_used',
            field=models.ManyToManyField(blank=True, to='portfolio.tag'),
        ),
    ]
