# Generated by Django 5.0.7 on 2024-08-05 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_projects_technologies_projects_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='link',
            new_name='demo',
        ),
    ]
